[package]
name = "rating-core"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.38", features = ["serde"] }
once_cell = "1.19.0"
ordered-float = "4.2.0"
serde = { version = "1.0.198", features = ["derive"] }
serde_json = "1.0.116"
